version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - chore
    open-pull-requests-limit: 20
  - package-ecosystem: cargo
    directory: "/espmonitor"
    schedule:
      interval: weekly
    labels:
      - chore
    open-pull-requests-limit: 20
  - package-ecosystem: cargo
    directory: "/cargo-espmonitor"
    schedule:
      interval: weekly
    labels:
      - chore
    open-pull-requests-limit: 20
