on:
  release:
    types:
      - published
name: release
jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Publish release
        run: ./release.sh ${{ secrets.CRATES_IO_TOKEN }}
